config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'animals#index'
  resources :animals, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:index, :show, :new, :create]
  end
  resources :bookings, only: :destroy
  resources :dashboard, only: [:index, :show]
  patch "/animals/:animal_id/bookings/:id/accept", to: "bookings#accept", as: :accept
  patch "/animals/:animal_id/bookings/:id/decline", to: "bookings#decline", as: :decline
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many_attached :photos
  has_many :bookings
  belongs_to :user
  validates :species, inclusion: { in: ["Horse", "Cow", "Pig", "Dog", "Chicken", "Cat", "Goat", "Sheep", "Duck", "Goose"] }
  validates :name, presence: true
  validates :species, presence: true
  validates :gender, presence: true
  validates :personality, presence: true
  validates :description, presence: true
  validates :care_level, presence: true
  validates :age, presence: true
  validates :price_per_day, presence: true
  validates :care_instructions, presence: true

  CARE_LEVEL = ["Easy", "Medium", "Hard"]

  include PgSearch::Model
  pg_search_scope :search_by_species,
    against: [ :species ],
    using: {
      tsearch: { prefix: true }
    }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # before_create :set_address

  # def set_address
  #   self.address = user.address
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :animal
  enum status: [:pending, :accepted, :declined]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :animals
  has_many :bookings
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  # before_action :set_animal, only: [:show]

  def index
    if params[:query].present?
      @animals = Animal.search_by_species(params[:query])
      if params[:search].present?
        @animals = @animals.where(care_level: params[:search])
      end
    else
      @animals = Animal.all
      if params[:search].present?
        @animals = @animals.where(care_level: params[:search])
      end
      @previous_search = ''
    end
  end

  def show
    @animal = Animal.find(params[:id])
    @markers = [{ lat: @animal.latitude, lng: @animal.longitude }]
    @booking = Booking.new
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user = current_user
    @animal.address = current_user.address
    if @animal.save
      redirect_to animal_path(@animal)
    else
      render :new
    end
  end

  private

  def set_animal
    @animal = Animal.find(params[:id])
  end

  def animal_params
    params.require(:animal).permit(
      :name,
      :species,
      :breed,
      :gender,
      :personality,
      :description,
      :care_level,
      :age,
      :price_per_day,
      :care_instructions,
      :photo,
      :title, :body, photos: []
      )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :photo])
  end
end

app/controllers/bookings_controller.rb
require 'date'

class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :destroy]
  
  def index
    @bookings = Booking.where("user = current_user")
  end

  def show
    @animal = Animal.find(params[:animal_id])
  end
  
  def create
    @animal = Animal.find(params[:animal_id])
    @user = current_user
    @booking = Booking.new(
      date_start: Date.new(params["booking"]["date_start(1i)"].to_i, params["booking"]["date_start(2i)"].to_i, params["booking"]["date_start(3i)"].to_i),
      date_end: Date.new(params["booking"]["date_end(1i)"].to_i, params["booking"]["date_end(2i)"].to_i, params["booking"]["date_end(3i)"].to_i),
      animal: @animal,
      user: @user
    )
    @total_price = calculate_total(@booking.date_start, @booking.date_end, @booking.animal.price_per_day)
    @booking.total_price = @total_price
    @booking.pending!
    if @booking.save
      redirect_to animal_booking_path(@animal, @booking)
    else
      render "animals/show"
    end
  end

  def destroy
    @booking.destroy
    redirect_to animal_bookings_path(@booking.animal), notice: 'Booking was canceled.'
  end

  def accept
    @booking = Booking.find(params[:animal_id])
    @booking.accepted!
    redirect_to dashboard_index_path, notice: 'Booking confirmed!'
  end

  def decline
    @booking = Booking.find(params[:animal_id])
    @booking.declined!
    redirect_to dashboard_index_path, notice: 'Booking declined!'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(params["booking"]["date_start(1i)"].to_i, params["booking"]["date_start(2i)"].to_i, params["booking"]["date_start(3i)"].to_i, params["booking"]["date_end(1i)"].to_i, params["booking"]["date_end(2i)"].to_i, params["booking"]["date_end(3i)"].to_i)
  end

  def calculate_total(date_start, date_end, price_per_day)
    num_of_days = date_end - date_start
    num_of_days * price_per_day
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @animals = Animal.where(user: current_user)
    @requests = Booking.where(user: current_user)
  end

  def show
    @animal = Animal.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/index.html.erb
<div class="header-container">
  <div class="banner">
    <%= image_tag 'jumbotron.jpg', class: 'img-banner' %>
  </div>
  <div class="header-text">
    <h1 class="header-h1">Did you ever take a sheep on a stroll through Görlitzer Park?</h1>
    <h4 class="header-h4">Rent a farm animal and have a unique, cuddly experience</h4>
  </div>

  <div>
    <%= form_tag animals_path, method: :get do %>
    <div class="search-bar">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "What type of farm animal are you looking for?"
      %>
      <%= submit_tag "Search", class: "search-button" %>
    </div>
    <% end %>
  </div>
</div>

<%= form_tag animals_path, method: :get do %>
<div class="container filter">
  <%= select_tag(:search, options_for_select(Animal::CARE_LEVEL, params[:search])) %>
  <%= hidden_field_tag :query, params[:query] %>
  <%= submit_tag "Filter by Difficulty", class: "filter-btn" %>
<% end %>
</div>


<% if @animals.count.positive? %>
  <h5 class="home-h3">These farm animals are cute and available</h5>
  <div class="container">
    <ul class = cards>
      <% @animals.each do |animal| %>
        <li class="card" style="background-image: url(<%= cl_image_path animal.photos.first.key %>)"><%= link_to animal.name, animal_path(animal) %></li>
      <% end %>
    </ul>
  </div>
<% else %>
  <div class="results-container">
    <h5>No farm animals match your search criteria.</h5> 
    <h5>There are lots of animals that would like to go on an adventure.</h5> 
    <h5>Please change your search criteria and try again!</h5>
  </div>
<% end %>

app/views/animals/new.html.erb
<div class="container">
  <h1 class="new-header"> <%= link_to"〈", root_path, class: "arrow" %> Add your lovely animal</h1>
</div>

<div class="container" id="new-form">
    <%= simple_form_for [@animal] do |f| %>
  <div class="form-categories">
      <%= f.input :name %>
      <%= f.input :species, :collection => %w[Horse Cow Pig Dog Chicken Cat Goat Sheep Duck Goose] %>
      <%= f.input :breed %>
      <%= f.input :gender, :collection => %w[Male Female] %>
      <%= f.input :personality %>
      <%= f.input :description %>
      <%= f.input :care_level, :collection => %w[Easy Medium Hard] %>
      <%= f.input :age %>
      <%= f.input :price_per_day %>
      <%= f.input :care_instructions %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit :class => "button" %>
    <% end %>
  </div>
</div>

app/views/animals/show.html.erb
<div class="show-header">
  <h1 class="show-header-h1"> <%= link_to"〈", root_path, class: "arrow" %> Meet <%= @animal.name %></h1>
</div>

<div class="container" id="show-container">


  <div class="show-img">
    <% @animal.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 350, width: 500, crop: :fill, radius: 10; %>
    <% end %>
    <div class="map-box">
      <div id="map"
        style="width: 100%; height: 300px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>

  <div class="show-profile">
    <p><%= image_tag 'user-circle-solid.svg', class: "avatar dropdown-toggle" %> <%= @animal.user.first_name %> <%= @animal.user.last_name %></p>
    <p><strong>Price per day</strong> <%= @animal.price_per_day %>€</p>
    <p><strong>Gender</strong>
      <% if @animal.gender == "Male" %>
        <i class="fas fa-mars gender"></i>
      <% else %>
        <i class="fas fa-venus gender"></i>
      <% end %>
    | <strong>Age</strong> <%= @animal.age %> |
    <% if @animal.breed == "" %>
    <% else %>
      <strong>Breed</strong> <%= @animal.breed %>
    <% end %>
    </p>
    <p><strong>Care level</strong> <%= @animal.care_level %></p>
    <p><strong>Personality</strong> <%= @animal.personality %></p>
    <p><strong>Description</strong> <%= @animal.description %></p>
    <p><strong>Care instructions</strong> <%= @animal.care_instructions %></p>

  <h4 class="create-booking">Book <%= @animal.name %> For An Adventure</h4>

    <div class="animal-show-date-booking">
      <%= simple_form_for [@animal, @booking] do |f| %>
      <%= f.input :date_start, label: "Date of Pickup" %>
      <%= f.input :date_end, label: "Date of Drop Off" %>
      <%= f.submit :class => "button" %>
      <% end %>
    </div>

  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <h1 class="new-header-booking"> <%= link_to"〈", animal_path(@animal), class: "arrow" %> Create New Booking for <%= @animal.name %></h1>
</div>

<div class="container" id="booking-container">
  <div class="booking-details">
    <h2>Your Booking Details</h2>
      <div class="detail-list">
        <ul>
          <li>Farm Animal: <%= @animal.name %></li>
          <li>Location: <%= @animal.user.address %></li>
          <li>What to Expect: <%= @animal.description %></li>
          <li>Price Per Day: <%= @animal.price_per_day %>€</li>
        </ul>
      </div>
  </div>
  <div class="booking-img">
    <% @animal.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 350, width: 500, crop: :fill, radius: 15; %>
    <% end %>
  </div>
</div>

<div class="date-booking">
  <%= simple_form_for [@animal, @booking] do |f| %>
  <%= f.input :date_start, label: "Date of Pickup" %>
  <%= f.input :date_end, label: "Date of Drop Off" %>
  <%= f.submit :class => "button" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
 <div class="header-container">
     <div class="banner">
    <%= image_tag 'horse.jpg', class: 'img-banner' %>
  </div>
    </div>
    <div class="header-text">
      <h1 class="bookings-header-h1">Yay! You and <%= @animal.name %> are going on an adventure together!</h1>
      

      <ul class="list-styling">
        <li>Start Date: <%= @booking.date_start %></li>
        <li>End Date: <%= @booking.date_end %></li>
        <li>Total Price: <%= @booking.total_price %>€</li>
        <li>Pick Up and Drop Off: <%= @animal.user.address%></li>
        <li>Owner Name: <%= @animal.user.first_name %> <%= @animal.user.last_name %></li>
      </ul>

  <%= link_to "Book more farm animals and impress more humans", root_path, class: "button", id: "btn-back" %>
    </div>
  </div>


</div>

app/views/dashboard/index.html.erb
<div class="show-header">
  <h1> <%= link_to"〈", root_path, class: "arrow" %> Your Dashboard</h1>
</div>

  <h5 class="bookings-h5">Your Bookings</h5>
  <div class="your-bookings-container">
      <% if @requests.count.positive? %>
        <% @requests.each do |request| %>
        <div class="booking-card">
          <div class="booking-img" style="background-image: url(<%= cl_image_path request.animal.photos.first.key %>)">
            <%= link_to request.animal.name, animal_path(request.animal) %>
          </div>
          <div class="booking-details">
            <ul class="list">
              <li><strong>Booking details</strong></li>
              <li><strong>Start Date</strong> <%= request.date_start %></li>
              <li><strong>End Date</strong> <%= request.date_end %></li>
              <li><strong>Status</strong> <%= request.status %></li>
            </ul>
          </div>
        </div>
        <% end  %>
      <% else %>
        <p>You haven't booked any farm animals yet! 😢 </p>
        <%= link_to "Search for Farm Animals", root_path, class: "button" %>
      <% end %>
  </div>

  <div>
    <h5 class="bookings-h5">Your Farm Animals for Rent</h5>
    <div class="your-animals-container">
      <% if @animals.count.positive? %>
        <% @animals.each do |animal| %>
          <div class="booking-img-badge position-relative" style="background-image: url(<%= cl_image_path animal.photos.first.key %>)">
            <%= link_to animal.name, animal_path(animal) %>
            <span class="badge">
              <%= link_to animal.bookings.where(status: "pending").count, dashboard_path(animal) %>
            </span>
          </div>
        <% end %>
      <% else %>
        <p>You have not listed any farm animals for rent.</p>
        <%= link_to "Rent Your Farm Animal", new_animal_path, class: "button" %>
      <% end %>
    </div>
  </div>

app/views/dashboard/show.html.erb
<div class="show-header">
  <h1 class="show-header-h1"> <%= link_to"〈", dashboard_index_path, class: "arrow" %> Booking Requests for <%= @animal.name %></h1>
</div>

<div class ="dash-request">
  <ul class="remove-dots">
    <% @animal.bookings.each do |booking| %>
      <li>
        <div class="request-card">
          <div class="request-details">
            <div class="request-img" style="background-image: url(<%= cl_image_path booking.animal.photos.first.key %>)">
              <%= link_to booking.animal.name, animal_path(booking.animal) %>
            </div>
            <ul class="request-list">
              <li><strong>Booking Details</strong></li>
              <li><strong>Start Date</strong> <%= booking.date_start %></li>
              <li><strong>End Date</strong> <%= booking.date_end %></li>
              <li><strong>Requester</strong> <%= booking.user.first_name %> <%= booking.user.last_name %></li>
              <li><strong>Status</strong> <%= booking.status.capitalize %></li>
            </ul>
          </div>
          <div class="request-buttons">
              <% if booking.pending? %>
                <%= link_to "Accept", accept_path(booking), class: "button", method: :patch, controller: :bookings_controller %>
                <%= link_to "Decline", decline_path(booking), class: "button", method: :patch, controller: :bookings_controller, data: { confirm: 'Are you sure you want to decline this booking?' } %>
              <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>farmily</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if params[:controller] == "animals" && params[:action] == "index" %>
      <%= render 'shared/hovering_navbar' %>
    <% else %>
     <%= render 'shared/navbar' %>
    <% end %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_hovering_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-transparent position-absolute w-100 z-index">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "farmily.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Rent Your Farm Animal", new_animal_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
        <%if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
            <%= image_tag 'user-circle-solid.svg', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_index_path, class: "dropdown-item" %>
            <%= link_to "Edit Your Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-transparent">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "farmily.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Rent Your Farm Animal", new_animal_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
              <%= image_tag 'user-circle-solid.svg', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_index_path, class: "dropdown-item" %>
            <%= link_to "Edit Your Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>